### ISSUE TITLE
validator-vest doesn't handle async tests

### ISSUE THREAD

**Issue by tylkomat** [pablo-abc/felte#119]
**Describe the bug**
An async test never fails.

**To Reproduce**
1. create a suite that includes an async test
```
const suite = create((data) => {
  test('email', 'Account already exists', () => Promise.reject());
};
```
2. The result is `{email: null}` 

**Expected behavior**
The suite should error on email with the message `Account already exists`.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 98.0.1
 - Version: felte@1.1.4, @felte/validator-vest@1.0.3, vest@4.3.0

**Additional context**
The [done](https://vest.vercel.app/docs/writing_your_suite/result_object#done) method should be used to handle async context.

**Comment by pablo-abc** [comment]
Good catch! And thanks for pointing to the fix on the documentation, simplified my work a lot!

Should be fixed in 1.0.4!

**Comment by tylkomat** [comment]
Thank you for fixing it so fast. Unfortunately Warnings have the same problem. 

I also noticed that sync errors are now not shown immediately anymore. Looks like the old and the new version have to be combined. Sync errors are returned right away, which is how the previews validator-vest version was working and async errors are submitted via done function. The problem is that this seems to be not possible with the current validate function layout.

**Comment by sysmat** [comment]
For me is not working:
```
"@felte/validator-vest": "^1.0.9",
"felte": "^1.2.2",
"vest": "^4.5.0"
```

**Comment by sysmat** [comment]
- still not working
```
"@felte/validator-vest": "^1.0.10",
"felte": "^1.2.3",
"vest": "^4.6.5"
```
- in https://vestjs.dev/  in section Try It Live: it works, so problem is not in vest

**Comment by sysmat** [comment]
- errors store is not working, when I try manually I see present vest async error test

```typescript
$: {
    f = {
      email: getValue($data, "email"),
      password: getValue($data, "password"),
      username: getValue($data, "username"),
    };

    console.log("form=", f);
    let result = validationContact(f, "username");
    console.log("result=", result.getErrors());
  }
```

- log:
```
result= {email: Array(1), password: Array(2), 
username: Array(1)}
email: ['Email is required']password: (2) 
['Password is required', 'is to short']
username: Array(1)
0: "Username already exists"length: 1[[Prototype]]: Array(0)[[Prototype]]: 
Object
```

**Comment by sysmat** [comment]
- "vest": "^4.6.7"
- "felte": "^1.2.5",
- "@felte/validator-vest": "^1.0.11",

vest async validation still not working

**Comment by sysmat** [comment]
it look like in vite dev server, vite bulid works better, but no smooth reactive with error store message
